spring.profiles.active: development
---
spring:
  application:
    name: ex-discovery
  profiles: development
server:
  port: 8761
eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
security:
  basic:
    enabled: false
management:
  endpoint:
    shutdown:
      enabled: true
    restart:
      enabled: true